blueprint:
  name: AWTRIX Calendar Color Configuration
  description: Configure colors for AWTRIX calendar display.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic to publish the colors.
      selector:
        text: {}
    header_color:
      name: Calendar Header Color
      description: Hex color code for the calendar header.
      selector:
        text: {}
    body_color:
      name: Calendar Body Color
      description: Hex color code for the calendar body.
      selector:
        text: {}
    text_color:
      name: Calendar Text Color
      description: Hex color code for the calendar text.
      selector:
        text: {}

action:
  - service: mqtt.publish
    data:
      topic: "{{ mqtt_topic }}"
      payload: >
        {
          "CHCOL": "{{ header_color }}",
          "CBCOL": "{{ body_color }}",
          "CTCOL": "{{ text_color }}"
        }
