blueprint:
  name: AWTRIX Calendar Color Configuration
  description: Configure colors for AWTRIX calendar display.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic to publish the colors.
      selector:
        text: {}
    header_color:
      name: Calendar Header Color
      description: Color setting for the calendar header.
      selector:
        color_rgb: {}
      default: [255, 0, 0]  # Красный по умолчанию
    body_color:
      name: Calendar Body Color
      description: Color setting for the calendar body.
      selector:
        color_rgb: {}
      default: [255, 255, 255]  # Белый по умолчанию
    text_color:
      name: Calendar Text Color
      description: Color setting for the calendar text.
      selector:
        color_rgb: {}
      default: [0, 0, 0]  # Черный по умолчанию

action:
  - service: mqtt.publish
    data:
      topic: "{{ mqtt_topic }}"
      payload: >
        {
          "CHCOL": "{{ header_color }}",
          "CBCOL": "{{ body_color }}",
          "CTCOL": "{{ text_color }}"
        }
