blueprint:
  name: AWTRIX Calendar Color Configuration
  description: Configure colors for AWTRIX calendar display.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic to publish the colors.
      selector:
        text: {}
    selected_device:
      name: Select Device
      description: Choose the AWTRIX device to send colors.
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Blueforcer
              model: AWTRIX 3
          multiple: true
    color_1:
      name: Color 1
      description: Color setting for the first element.
      selector:
        color_rgb: {}
      default: [255, 0, 0]  # Красный по умолчанию
    color_2:
      name: Color 2
      description: Color setting for the second element.
      selector:
        color_rgb: {}
      default: [255, 255, 255]  # Белый по умолчанию
    color_3:
      name: Color 3
      description: Color setting for the third element.
      selector:
        color_rgb: {}
      default: [0, 0, 0]  # Черный по умолчанию

action:
  - service: mqtt.publish
    data:
      topic: "{{ mqtt_topic }}"
      payload: >
        {
          "CHCOL": "{{ color_1 }}",
          "CBCOL": "{{ color_2 }}",
          "CTCOL": "{{ color_3 }}"
        }
